id: I4D98D424
legacy_id: P004623
ocr_import_info:
  bdrc_scan_id: W22380
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T07:24:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:26:32.901606+00:00'
last_modified: 2022-09-02 07:44:08.752128
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22380
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22380
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམིགས་བརྩེ་མའི་བེའུ་བུམ།
statistics:
  ocr_word_mean_confidence_index: 0.6737648744660063
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I3043:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3043
      total_pages: 768
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3043.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6917186014039741
    legacy_id: v002
  I3042:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3042
      total_pages: 606
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3042.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6635014643278443
    legacy_id: v001
  I3044:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3044
      total_pages: 664
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3044.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6640371977975856
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
